#!/usr/bin/env bash
#
# spotify-now: info on the current spotify song
# https://github.com/getmicah/spotify-now
#
# Created by Micah Cowell
# https://github.com/getmicah


# get mpris2 dbus status of spotify player
META=`dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'`
INFO=""

getInfo () {
    # determine row in meta list
    row="1"
    if [ "$1" = "artist" ] || [ "$1" = "albumArtist" ]
    then
        row="2"
    fi
    echo $(echo "$META" | grep -m 1 "xesam:$1" -b$row | tail -n1 | cut -d'"' -f2)
}

for arg in "$@"
do
    case "$arg" in
       trackid) INFO="$INFO $(getInfo $arg)"
       ;;
       artUrl) INFO="$INFO $(getInfo $arg)"
       ;;
       album) INFO="$INFO $(getInfo $arg)"
       ;;
       albumArtist) INFO="$INFO $(getInfo $arg)"
       ;;
       artist) INFO="$INFO $(getInfo $arg)"
       ;;
       title) INFO="$INFO $(getInfo $arg)"
       ;;
       *) INFO="$INFO $arg"
       ;;
       ) echo "Error: You need to "
    esac
done

echo $INFO
