.Dd Nov 4, 2022
.Dt SPMD 1
.Os
.Sh NAME
.Nm spmd
.Nd spotify metadata
.Sh SYNOPSIS
.Nm
.Op Fl P Ar message
.Op Fl S Ar message
.Op Ar metadata
.Sh DESCRIPTION
The
.Nm
utility displays metadata from the proprietary Spotify client.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl P Ar message
Display
.Ar message
if paused.
.It Fl S Ar message
Display
.Ar message
if Spotify is closed.
.It Ar metadata
Macros: %album, %artist, %title, %discNumber, %trackNumber.
.El
.Sh Examples
.Pp
.Dl $ spmd '%artist - %title'
.Dl Vince Guaraldi - Linus And Lucy
.Pp
Spotify is paused:
.Pp
.Dl $ spmd -P '<paused>' '%album'
.Dl A Charlie Brown Christmas <paused>
.Pp
Spotify is closed:
.Pp
.Dl $ spmd -S closed
.Dl closed