#!/usr/bin/env bash
#
# https://github.com/getmicah/spotify-now


# get mpris2 dbus status of spotify player
META=`dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'`

getAlbum () {
    echo $(echo "$META" | grep -m 1 "xesam:album" -b1 | tail -n1 | cut -d'"' -f2)
}

getArtist () {
    echo $(echo "$META" | grep -m 1 "xesam:artist" -b2 | tail -n1 | cut -d'"' -f2)
}

getTitle () {
    echo $(echo "$META" | grep -m 1 "xesam:title" -b1 | tail -n1 | cut -d'"' -f2)
}


INFO=""
if [[ $# -eq 0 ]] ; then
    echo "Hello, this is spotify-now:"
    echo "https://github.com/getmicah/spotify-now"
    exit 0
fi
for arg in "$@"
do
    case "$arg" in
       %album) INFO="$INFO $(getAlbum)"
       ;;
       %artist) INFO="$INFO $(getArtist)"
       ;;
       %title) INFO="$INFO $(getTitle)"
       ;;
       *) INFO="$INFO $arg"
       ;;
       *) INFO="$INFO $arg"
       ;;
    esac
done

echo $INFO
