#!/bin/sh

album() {
    res=$(echo "$META" | grep -m 1 "xesam:album" -b1 | tail -n1)
    res="${res%\"*}"
    res="${res#*\"}"
    echo "$res"
}

artist() {
    res=$(echo "$META" | grep -m 1 "xesam:artist" -b2 | tail -n1)
    res="${res%\"*}"
    res="${res#*\"}"
    if [[ "$res" == "" ]]; then
        echo "Ad"
    else
        echo "$res"
    fi
}

disc() {
    res=$(echo "$META" | grep -m 1 "xesam:discNumber" -b1 | tail -n1)
    res="${res#*3}"
    res="${res#*2}"
    echo "$res"
}

title() {
    res=$(echo "$META" | grep -m 1 "xesam:title" -b1 | tail -n1)
    res="${res%\"*}"
    res="${res#*\"}"
    echo "$res"
}

track() {
    res=$(echo "$META" | grep -m 1 "xesam:trackNumber" -b1 | tail -n1)
    res="${res#*3}"
    res="${res#*2}"
    echo "$res"
}

errorMsg() {
    echo "Error: invalid argument"
    echo "help: https://github.com/getmicah/spotify-now"
    exit 1
}

# help message
helpMsg () {
    echo "usage: spotify-now [-ipe]"
    echo "help: https://github.com/micahco/spotify-now"
    exit 1
}

if [[ $# -eq 0 ]]; then
    helpMsg;
    exit 1;
fi


# parse args
INFO=""
PAUSED=""
ERROR=""
ESCAPE=false
while getopts i:p:e: flag
do
    case "${flag}" in
        i) INFO=${OPTARG};;
        p) PAUSED=${OPTARG};;
        e) ERROR=${OPTARG};;
	  ?) exit 1;
    esac
done
if [[ $* == *--escape* ]]; then
	ESCAPE=true
	echo "ESC"
fi

pid=`pidof spotify | wc -l`
if [[ "$pid" != 1 ]]; then
	if [[ "$ERROR" != "" ]]; then
    		echo "$ERROR"
	else
		echo "pidof spotify: $pid"
	fi
else
	playback=`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus' | grep -o Paused`
	if [[ "$playback" == "Paused" && "$PAUSED" != "" ]]; then
		echo "$PAUSED"
	elif [[ "$INFO" != "" ]]; then
   		META=`dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'`
   		INFO="${INFO//"%album"/$(album)}"
   		INFO="${INFO//"%artist"/$(artist)}"
   		INFO="${INFO//"%disc"/$(disc)}"
   		INFO="${INFO//"%title"/$(title)}"
   		INFO="${INFO//"%track"/$(track)}"
		if [ "$ESCAPE" = true ]; then
			INFO="${INFO//&/&amp;}"
			INFO="${INFO//</&lt;}"
			INFO="${INFO//>/&gt;}"	
			INFO="${INFO//\"/&quot;}"
			INFO="${INFO//\\/\\\\}"
		fi
		echo $INFO
	else
		helpMsg
	fi
fi
